### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by illyrius666** [ventojs/webstorm-vento#4]
**TODO**
- [x] project desc: `Vento for JetBrains's WebStorm IDE`
- [x] plugin icons (preferably in .svg)
- [x] README
- [x] change namespace of plugin to that of this org
- [x] add main branch protection
- [x] add proper issue templates for this project
- [x] add LICENSE.md
- [x] add CODE_OF_CONDUCT.md
- [ ] fix CodeQL
- [x] fix security issues for workflows
- [ ] remake workflows
- [ ] the implementation of vento into webstorm:
  - [ ] You can take a look to the [VScode extension](https://github.com/ventojs/vscode-vento/blob/main/syntaxes/vento.tmLanguage.json) but basically it uses the HTML syntax as base with the following changes:
  - [ ]     Everything between {{> and }} is pure [JavaScript](https://github.com/ventojs/vscode-vento/blob/main/syntaxes/vento.tmLanguage.json#L34-L44).
  - [ ]     Everything between {{ and }} is Vento code, which is also JavaScript but [with some special keywords](https://github.com/ventojs/vscode-vento/blob/main/syntaxes/vento.tmLanguage.json#L60).
  - [ ]     Everything between {{# and#}} is [commented code](https://github.com/ventojs/vscode-vento/blob/main/syntaxes/vento.tmLanguage.json#L15-L17).
  - [ ]     And it should have support [for front matters](https://github.com/ventojs/vscode-vento/blob/main/syntaxes/vento.tmLanguage.json#L63).

**Comment by illyrius666** [comment]
@oscarotero could you link the issue at vento to here?

**Comment by oscarotero** [comment]
Done! https://github.com/ventojs/vento/issues/75

**Comment by illyrius666** [comment]
@oscarotero somehow i dont have the rights to push from my IDE to this repo?
```
remote: Permission to ventojs/webstorm-vento.git denied to illyrius666.
fatal: unable to access 'https://github.com/ventojs/webstorm-vento/': The requested URL returned error: 403
```

**Comment by oscarotero** [comment]
No idea. You have the highest available role
Did you clone the repo with SSH?

**Comment by illyrius666** [comment]
aa i see i cloned it with https, woops

**Comment by illyrius666** [comment]
@oscarotero okay i cloned it with ssh but i still dont have permission

**Comment by oscarotero** [comment]
do you have your ssh key configured in GitHub? (Settings > SSH and GPG keys)

**Comment by illyrius666** [comment]
@oscarotero didnt work, also just discovered that intellij itself is behaving weird, because commiting in intellij and then using github desktop to push it works fine..

**Comment by zenwork** [comment]
Most of the issues in the TODO list are resolved with #25 .
